### ISSUE TITLE
Set version ranges using ^ in package.json to deduplicate transitive dependencies

### ISSUE THREAD

**Issue by thehenrytsai** [TBD54566975/dwn-sdk-js#385] opened 2023-05-30 22:26 UTC
### Background:
This ask came from #315. 

The original intent of version lock was to prevent any chance of unexpected dependency issues. But if it deals more pain by default, a case (the above referenced issue) can be made to relax the restriction.

The alternative is to have mono-repos and locking our dependency versions between projects. But this approach will not help with externally managed projects like `ion-tools` in which case we will need to fork.

### Task Details:
1. Update all dependencies in `package.json` to latest
2. Relax version restriction by adding `^` to the version number

## Picking Up This Issue:
- If you'd like to work on this, please comment "picking this up" below, and I'll assign the issue to you 

## Questions:
- If you need assistance or clarification, feel free to comment below.
- Feeling overwhelmed? Join our [`#hack-together` channel](https://discord.gg/tbd) and collaborate with a buddy.
- New to open-source? Check out our [Hacktober `#getting-started` channel](https://discord.gg/tbd).
- [Leaderboard](https://github.com/TBD54566975/developer.tbd.website/issues/721): Check your ranking after finishing this task.

### Resources:
- **Creating a Pull Request**: If you're new to GitHub and unsure how to create a pull request, follow this [step-by-step guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request).

Remember, communication is key! If you have any questions or face any challenges, we're here to help so please don't hesitate to reach out.

Good Luck! 🍁

**Comment by shamilovtim** [comment] 2023-06-12 19:46
Some examples of why we shouldn't be locking to exact versions in our SDK consumed by other users:

2 versions of @nobile/ed25519, 3 versions of @noble/secp256k1, 
<img width="1027" alt="Screenshot 2023-06-12 at 3 39 49 PM" src="https://github.com/TBD54566975/dwn-sdk-js/assets/3495974/611bb1c8-e6ef-49e3-a9ad-36ccd50a8312">

2 versions of secp256k1 (and isnt this already a duplicate of the above secp256k1 package?)
<img width="1028" alt="Screenshot 2023-06-12 at 3 39 33 PM" src="https://github.com/TBD54566975/dwn-sdk-js/assets/3495974/d003fcad-1e01-4e9d-84c3-fd9c3205be9a">

a whopping 3 versions of readable stream, which was already 220kb. this is **1.3mb worth** of `readable-stream`
<img width="1021" alt="Screenshot 2023-06-12 at 3 39 04 PM" src="https://github.com/TBD54566975/dwn-sdk-js/assets/3495974/1025db6d-6b26-4849-9429-42bbced43c3d">

3 versions of multiformats worth a whopping **3.6 megabytes**:
<img width="1024" alt="Screenshot 2023-06-12 at 3 45 02 PM" src="https://github.com/TBD54566975/dwn-sdk-js/assets/3495974/7a5dae52-26b4-4c04-8e52-2df05efdc0c2">

and this is the best case scenario since i ran this in a prototype. in an end user's package they'll have even more duplicates since they'll be using other packages from the community

**Comment by shamilovtim** [comment] 2023-06-12 19:48
locking to exact versions makes sense for a product but does not make sense for a library which depends on other libraries which recursively depend on other libraries

**Comment by Petsamuel** [comment] 2023-10-10 18:09
picking this up

**Comment by EbonyLouis** [comment] 2023-10-16 17:09
@Petsamuel Assigned 🥳 good luck!

**Comment by diehuxx** [comment] 2023-10-19 18:35
We've decided that version ranges aren't worth it for us right now. The potential benefits of slimming package size don't outweigh the risk of introducing breaking changes in upstream deps or causing inconsistent issues that result from local package versions being different depending on when someone runs npm install. In the future, when we revisit package size optimization, we'll revisit this issue.

**Closed by diehuxx** 2023-10-19 18:35 UTC
Labels: good first issue, build
