### ISSUE TITLE
Ensure protocol configurations encapsulate their valid record members to avoid breaking convergence

### ISSUE THREAD

**Issue by csuwildcat** [TBD54566975/dwn-sdk-js#335] opened 2023-05-01 14:22 UTC
Presently, if you reconfigure an already installed protocol that has records that fell under it, and the new configuration changes some things that would make previously valid records under the old protocol rules invalid under the new rules, it can create a split brain state if old records are replayed against new rules. To avoid this, we must tie records to a given protocol configuration and seal up the records that are to be retained against them when reconfiguration occurs.

**Comment by thehenrytsai** [comment] 2024-09-14 01:11
Dupe of #740.

**Closed by thehenrytsai** 2024-09-14 01:11 UTC
Labels: duplicate, feature
