### ISSUE TITLE
Bump transitive dependencies to latest along with ion-tools

### ISSUE THREAD

**Issue by shamilovtim** [TBD54566975/dwn-sdk-js#315] opened 2023-04-18 17:19 UTC
## Context

In a package that uses dwn sdk and ion tools, the transitive dependencies start to look like this:
![image](https://user-images.githubusercontent.com/3495974/232854128-e90d6e5d-5817-4918-9f18-ce9488a9ce6e.png)

Multiple versions of unix-fs, multiformats, interface-blockstore, and so on. Many transitive dependencies are duplicated 3 or 4 times with different major versions pulled in.

This task can be broken down further to specific dependencies, but that's a detail for the OSE team.

Fixes:
- [ ] bump all dependencies in dwn sdk to latest 
- [ ] bump all dependencies in ion tools to latest
- [ ] make sure that ion tools and dwn sdk rely on the same versions of dependencies

**Comment by thehenrytsai** [comment] 2023-04-28 20:18
This is essentially a duplicate of #245, but with additional requirements with `ion-tools`.

**Comment by thehenrytsai** [comment] 2023-05-30 20:04
@shamilovtim, bumped `dwn-sdk` version to latest in #245, please feel free to file an issue in `ion-tools` to update it's IPFS related dependencies if you are still having problem .

**Comment by shamilovtim** [comment] 2023-05-30 20:42
Related: https://github.com/decentralized-identity/ion-tools/issues/53

**Comment by shamilovtim** [comment] 2023-05-30 22:04
I forgot to call this out: it isn’t just the ipfs ones. Same for dag/cbor , ipld, anything achingbrain, and anything paulmiller. Pretty much all of them should be permissive about minor versions, and all of them should probably match across our open source projects so we aren’t burdening projects with 2x, 3x, 4x of the same heavy crypto based dependencies resolving.

**Comment by thehenrytsai** [comment] 2023-05-30 22:28
Closing this issue with a targeted issue for action #385.

**Comment by thehenrytsai** [comment] 2023-05-30 23:41
Reopening. The issue asks to update all dependencies, not just IPFS related ones.

**Comment by thehenrytsai** [comment] 2023-06-14 18:45
#396 should address this issue on the DWN SDK side. Feel free to reference this commit in issue(s) in ION repo(s).

**Closed by thehenrytsai** 2023-06-14 18:45 UTC
Labels: good first issue, build
